[package]
name = "cdn_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
resolve-path = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.1"


[[bin]]
name = "cdn"
path = "src/main.rs"

